version: '3.4'

services:
  react-ui:
    stdin_open: true
    tty: true
    image: react-ui
    volumes:
      - ../public:/dbs-kopilo/public
      - ../src:/dbs-kopilo/src
      - ../package.json:/dbs-kopilo/package.json
      - ../package-lock.json:/dbs-kopilo/package-lock.json
    ports:
      - ${UI_HOST_PORT}:${UI_SERVICE_PORT}
    build:
      context: ../
      dockerfile: dockerbuild/Dockerfile
