name: RSpec Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2

    - name: Set up Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Bundle install
      run: |
        gem install bundler
        bundle install

    - name: Run RSpec tests
      run: bundle exec rspec spec/models/dispute_spec.rb spec/models/paynow_spec.rb
